-- Original version ls13: less engine braking effect
-- by slin2R
-- Vielen Dank für die Freigabe!
-- Modification to: more engine braking effect by twizzle
-- LS 15 by s4t4n less effect
-- LS 17 by s4t4n less effect modhub
-- LS 19 by s4t4n less effect modhub mit Genehmigung an Patar
-- s4t4n Motorbremse auf ein reales Maß erstellt

-- local version = "1.0.3   beta (02.12.2018)";
-- local version = "1.0.5.0 beta (28.12.2018)";
-- local version = "1.0.6.0 beta (01.01.2019)";
-- local version = "1.0.6.1 beta (02.01.2019)";
-- local version = "0.0.0.1 alpha (15.12.2021)"

-- NO MORE THIEFS PLEASE !
-- NO MORE THIEFS PLEASE !
-- NO MORE THIEFS PLEASE !
-- NO MORE THIEFS PLEASE !
-- NO MORE THIEFS PLEASE !
-- NO MORE THIEFS PLEASE !
-- NO MORE THIEFS PLEASE !
